### ISSUE TITLE
scrollbar show during switch

### ISSUE THREAD

**Issue by czzonet** [Krutie/distraction-free-vue-form#2]
scrollbar width affect elements position during switching

may you can fix like this:

```css
::-webkit-scrollbar {
width:0px;
}
```
